const ACTION_TYPES = {
  APP_LOGGED_IN: 'APP.LOGGED_IN',
  APP_SET_USER_DATA: 'APP_SET_USER_DATA',
  APP_TOGGLE_SIDE_BAR: 'APP.TOGGLE_SIDE_BAR',
  APP_SET_HEADER_CLASS: 'APP_SET_HEADER_CLASS',
  APP_SET_PICKED_SLOTS : 'APP_SET_PICKED_SLOTS'
};

export default ACTION_TYPES;
